# Generated by Django 5.1.7 on 2025-03-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='author',
        ),
        migrations.AddField(
            model_name='award',
            name='authors',
            field=models.ManyToManyField(to='myproject.author'),
        ),
    ]
